simulation:
  start_time: "2020-09-01 06:00:00"
  end_time:   "2020-09-01 18:00:00"
  step_seconds: 60
  bsa_min_m: 30
  bsa_max_m: 130
  turbine_influence_m: 200

model:
  inputs:
    habitat_raster: null   # e.g., data/external/habitat_prob.tif (0..1)
    dem_raster: null       # e.g., data/external/dem.tif
    wind_u_raster: null    # e.g., data/external/wind_u.tif (m/s)
    wind_v_raster: null    # e.g., data/external/wind_v.tif (m/s)
    crs_epsg: 4326

  weights:
    w_habitat: 1.0
    w_wind: 0.6
    w_target: 0.8
    w_slope_penalty: 0.4
    w_turbine_avoid: 0.6
    softmax_beta: 2.5

  altitude_priors:
    breeding_mean: 20
    breeding_sd: 10
    foraging_mean: 10
    foraging_sd: 6
    commuting_mean: 50
    commuting_sd: 20
    displaying_mean: 80
    displaying_sd: 20
    migrating_mean: 80
    migrating_sd: 20
    roosting_mean: 0
    roosting_sd: 1

  turbines:
    - {lat: -33.210, lon: 18.110, rotor_radius_m: 60, rotor_min_m: 30, rotor_max_m: 130}

  agents:
    - id: 1
      start_lat: -33.195
      start_lon: 18.096
      state: breeding
      sex: male
      nest_lat: -33.195
      nest_lon: 18.096
      roost_lat: -33.230
      roost_lon: 18.120